### ISSUE TITLE
privkey symlink rewritten on every execution

### ISSUE THREAD

**Issue by petercolberg** [hlandau/acmetool#164]
Currently acmetool rewrites the symbolic links `ACME_STATE_DIR/certs/*/privkey` on every execution. In the spirit of `make`, acmetool should preserve existing symlinks when the target/owner/permissions match the requirements.

**Comment by karlmdavis** [comment]
Note: This is breaking things for me, as I have a non-root process (OpenLDAP/`slapd`) that I need to give access to the private key via ACL (i.e. `setfacl`). Because the symlink leeps getting rewritten, my custom permissions keep disappearing.
