### ISSUE TITLE
Implement account deactivation

### ISSUE THREAD

**Issue by nhooyr** [hlandau/acmetool#181]
Is there any way to do [this](https://github.com/xenolf/lego/blob/58ead760661b523a76dd4bb099352f5a2da760c1/acme/client.go#L210) with acmetool?

**Comment by hlandau** [comment]
It looks like account deletion has been removed from the RFC in favour of deactivation, but boulder has yet to support this. So I'll probably hold off until then.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
