### ISSUE TITLE
ACMEv2 progress?

### ISSUE THREAD

**Issue by athanp** [hlandau/acmetool#314]
Any progress finalizing acme v2 implementation?

**Comment by athanp** [comment]
No answer after 10 days...
I assume we now have another "great but dead opensource project"😄

**Comment by tallship** [comment]
Yes. Absolutley. "...dead opensource project".

I've been a Slackware user for 25 years. You echo a hollow, rehtorical question often predicated upon a myriad of frustrations. Here's the deal. It works, is relevant, and to move forward all one needs ever do if their impatient or disatisfied, is click the little 'fork' button up there on the top of the project page.

I run a lot of really old software on my brand shiney new OSes, and I can tell you that even though some of these old favs are three and seven and more years old, I prefer using those to the newer ones, especially when considering that there is often replacement software in terms of alternative FOSS projects.

I customize what I need, watch for security issues, and continue to use something with less complexity than I actually need. wrt the LE experiment become de facto standard, I also run something called "le". You won't find it in the repos, it's been renamed, and I don't run that more modern, and much more sophisticated, Bash LE client.

When installing on a new machine, I install one of a couple of much older (and lightly customized) versions from my fork of the project a couple of years back.

I encourage you to investigate the ramifications of the passive-aggressive implication that a project is dead, or irrelevant, as such is usually much further from the truth than is good for all of us here in the community - especially yourself.

**Comment by simonszu** [comment]
To play devil's advocate: acmetool will be irrelevant in around 9 months since letsencrypt will shutdown acme v1, and acmetool has no implementation of v2.

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by athanp** [comment]
Hate to admit that but I've already migrated to [Lego]https://github.com/go-acme/lego which supports v2 since last year

**Comment by hlandau** [comment]
A beta of ACMEv2 support is now available, see https://github.com/hlandau/acmetool/issues/322.
