### ISSUE TITLE
Let's Encrypt ACMEv2 compatible

### ISSUE THREAD

**Issue by dnohr** [hlandau/acmetool#333]
Hi,

Thanks for making this software.

I'm still getting the warnings from Let's Encrypt regarding the ACMEv1 API calls on Ubuntu 18.04.

Will there be an official release to resolve this issue or is the project dead?

Message from Let's Encrypt:
> Beginning June 1, 2020, we will stop allowing new domains to validate using
> the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
> then, or certificate issuance will fail.

Thanks.

**Comment by skinkie** [comment]
https://github.com/hlandau/acmetool/issues/322

**Comment by dnohr** [comment]
> #322

Thanks for the follow-up, decided to change my setup to [getssl](https://github.com/srvrco/getssl). Highly recommended for anyone who is searching for a bash alternative. Will close this issue. Thanks!
